import {
  Atom,
  Binary,
  Blocks,
  Braces,
  CodeXml,
  File,
  FileCode,
  FileText,
  FileImage,
  FileArchive,
  FileAudio,
  FileVideo,
  FileSpreadsheet,
  Folder,
  Coffee,
  Container,
  Wrench,
  BookOpen,
  GitBranch,
  Package,
  PackageOpen,
  Flame,
  Database,
  Disc3,
  FileCog,
  FileJson2,
  FileKey2,
  FileLock2,
  FileTerminal,
  FileType2,
  FlaskConical,
  Gem,
  Hash,
  Presentation,
  type LucideIcon,
} from 'lucide-react';

/** 文件图标映射。 */
export interface IconMapping {
  icon: LucideIcon;
  color: string;
}

/** 根据文件名和是否目录获取图标。 */
export function getFileIcon(filename: string, isDirectory: boolean): IconMapping {
  if (isDirectory) return { icon: Folder, color: '#54AEFF' };

  const baseName = filename.split('/').pop() ?? filename;
  const normalizedName = baseName.toLowerCase();

  // 特殊文件名
  const specialNames: Record<string, IconMapping> = {
    dockerfile: { icon: Container, color: '#2496ED' },
    'docker-compose.yml': { icon: Container, color: '#2496ED' },
    'docker-compose.yaml': { icon: Container, color: '#2496ED' },
    'compose.yml': { icon: Container, color: '#2496ED' },
    'compose.yaml': { icon: Container, color: '#2496ED' },
    '.dockerignore': { icon: Container, color: '#2496ED' },
    makefile: { icon: Wrench, color: '#427819' },
    'cmakelists.txt': { icon: Wrench, color: '#064F8C' },
    jenkinsfile: { icon: FileTerminal, color: '#D33833' },
    procfile: { icon: FileTerminal, color: '#79589F' },
    readme: { icon: BookOpen, color: '#083FA1' },
    'readme.md': { icon: BookOpen, color: '#083FA1' },
    'package.json': { icon: Package, color: '#CB3837' },
    'package-lock.json': { icon: FileLock2, color: '#CB3837' },
    'bun.lock': { icon: FileLock2, color: '#FBF0DF' },
    'cargo.toml': { icon: PackageOpen, color: '#CE422B' },
    'cargo.lock': { icon: FileLock2, color: '#CE422B' },
    '.gitignore': { icon: GitBranch, color: '#F05032' },
    '.bashrc': { icon: FileTerminal, color: '#4EAA25' },
    '.zshrc': { icon: FileTerminal, color: '#4EAA25' },
    '.profile': { icon: FileTerminal, color: '#4EAA25' },
  };
  if (specialNames[normalizedName]) return specialNames[normalizedName];

  // 扩展名映射
  const ext = '.' + (filename.split('.').pop() ?? '').toLowerCase();
  const extMap: Record<string, IconMapping> = {
    '.rs': { icon: Blocks, color: '#F05A35' },
    '.py': { icon: FlaskConical, color: '#3776AB' },
    '.pyw': { icon: FlaskConical, color: '#3776AB' },
    '.ipynb': { icon: FlaskConical, color: '#F37626' },
    '.js': { icon: Braces, color: '#F7DF1E' },
    '.mjs': { icon: Braces, color: '#F7DF1E' },
    '.cjs': { icon: Braces, color: '#F7DF1E' },
    '.ts': { icon: Braces, color: '#3178C6' },
    '.mts': { icon: Braces, color: '#3178C6' },
    '.cts': { icon: Braces, color: '#3178C6' },
    '.tsx': { icon: Atom, color: '#61DAFB' },
    '.jsx': { icon: Atom, color: '#61DAFB' },
    '.go': { icon: Binary, color: '#00ADD8' },
    '.java': { icon: Coffee, color: '#ED8B00' },
    '.c': { icon: Binary, color: '#A8B9CC' },
    '.cpp': { icon: Binary, color: '#00599C' },
    '.cs': { icon: Hash, color: '#9B4F96' },
    '.rb': { icon: Gem, color: '#CC342D' },
    '.php': { icon: Braces, color: '#777BB4' },
    '.swift': { icon: Flame, color: '#F05138' },
    '.json': { icon: FileJson2, color: '#F7DF1E' },
    '.jsonc': { icon: FileJson2, color: '#F7DF1E' },
    '.yaml': { icon: FileCog, color: '#CB171E' },
    '.yml': { icon: FileCog, color: '#CB171E' },
    '.toml': { icon: FileCog, color: '#9C4121' },
    '.xml': { icon: CodeXml, color: '#0060AC' },
    '.env': { icon: FileKey2, color: '#ECD53F' },
    '.md': { icon: FileText, color: '#083FA1' },
    '.txt': { icon: FileText, color: '#6B7280' },
    '.html': { icon: CodeXml, color: '#E34F26' },
    '.htm': { icon: CodeXml, color: '#E34F26' },
    '.vue': { icon: CodeXml, color: '#42B883' },
    '.svelte': { icon: CodeXml, color: '#FF3E00' },
    '.css': { icon: Hash, color: '#1572B6' },
    '.scss': { icon: Hash, color: '#CC6699' },
    '.sass': { icon: Hash, color: '#CC6699' },
    '.less': { icon: Hash, color: '#1D365D' },
    '.png': { icon: FileImage, color: '#9333EA' },
    '.jpg': { icon: FileImage, color: '#9333EA' },
    '.jpeg': { icon: FileImage, color: '#9333EA' },
    '.gif': { icon: FileImage, color: '#9333EA' },
    '.svg': { icon: FileImage, color: '#9333EA' },
    '.zip': { icon: FileArchive, color: '#D97706' },
    '.tar': { icon: FileArchive, color: '#D97706' },
    '.gz': { icon: FileArchive, color: '#D97706' },
    '.7z': { icon: FileArchive, color: '#D97706' },
    '.rar': { icon: FileArchive, color: '#D97706' },
    '.mp3': { icon: FileAudio, color: '#10B981' },
    '.wav': { icon: FileAudio, color: '#10B981' },
    '.flac': { icon: FileAudio, color: '#10B981' },
    '.mp4': { icon: FileVideo, color: '#EF4444' },
    '.avi': { icon: FileVideo, color: '#EF4444' },
    '.mkv': { icon: FileVideo, color: '#EF4444' },
    '.csv': { icon: FileSpreadsheet, color: '#059669' },
    '.xls': { icon: FileSpreadsheet, color: '#059669' },
    '.xlsx': { icon: FileSpreadsheet, color: '#059669' },
    '.sh': { icon: FileTerminal, color: '#4EAA25' },
    '.bash': { icon: FileTerminal, color: '#4EAA25' },
    '.zsh': { icon: FileTerminal, color: '#4EAA25' },
    '.fish': { icon: FileTerminal, color: '#4EAA25' },
    '.bat': { icon: FileTerminal, color: '#4EAA25' },
    '.cmd': { icon: FileTerminal, color: '#4EAA25' },
    '.ps1': { icon: FileTerminal, color: '#2671BE' },
    '.psm1': { icon: FileTerminal, color: '#2671BE' },
    '.sql': { icon: Database, color: '#336791' },
    '.db': { icon: Database, color: '#336791' },
    '.sqlite': { icon: Database, color: '#0F80CC' },
    '.sqlite3': { icon: Database, color: '#0F80CC' },
    '.pem': { icon: FileKey2, color: '#D4A72C' },
    '.key': { icon: FileKey2, color: '#D4A72C' },
    '.crt': { icon: FileKey2, color: '#D4A72C' },
    '.cer': { icon: FileKey2, color: '#D4A72C' },
    '.p12': { icon: FileKey2, color: '#D4A72C' },
    '.pfx': { icon: FileKey2, color: '#D4A72C' },
    '.ttf': { icon: FileType2, color: '#7C3AED' },
    '.otf': { icon: FileType2, color: '#7C3AED' },
    '.woff': { icon: FileType2, color: '#7C3AED' },
    '.woff2': { icon: FileType2, color: '#7C3AED' },
    '.eot': { icon: FileType2, color: '#7C3AED' },
    '.ppt': { icon: Presentation, color: '#D24726' },
    '.pptx': { icon: Presentation, color: '#D24726' },
    '.odp': { icon: Presentation, color: '#D24726' },
    '.keynote': { icon: Presentation, color: '#2F70C0' },
    '.msi': { icon: PackageOpen, color: '#2563EB' },
    '.exe': { icon: PackageOpen, color: '#2563EB' },
    '.deb': { icon: PackageOpen, color: '#A81D33' },
    '.rpm': { icon: PackageOpen, color: '#CC0000' },
    '.apk': { icon: PackageOpen, color: '#3DDC84' },
    '.aab': { icon: PackageOpen, color: '#3DDC84' },
    '.ipa': { icon: PackageOpen, color: '#0A84FF' },
    '.iso': { icon: Disc3, color: '#64748B' },
    '.dmg': { icon: Disc3, color: '#64748B' },
    '.img': { icon: Disc3, color: '#64748B' },
  };
  if (extMap[ext]) return extMap[ext];

  const extensionGroups: Array<{ extensions: readonly string[]; mapping: IconMapping }> = [
    {
      extensions: [
        '.asm',
        '.s',
        '.h',
        '.hpp',
        '.hxx',
        '.cc',
        '.cxx',
        '.m',
        '.mm',
        '.swift',
        '.kt',
        '.kts',
        '.scala',
        '.groovy',
        '.dart',
        '.lua',
        '.rb',
        '.php',
        '.php3',
        '.php4',
        '.php5',
        '.phtml',
        '.pl',
        '.pm',
        '.r',
        '.rmd',
        '.jl',
        '.hs',
        '.lhs',
        '.elm',
        '.ex',
        '.exs',
        '.erl',
        '.hrl',
        '.fs',
        '.fsx',
        '.fsi',
        '.vb',
        '.vbs',
        '.ps1',
        '.psm1',
        '.psd1',
        '.sh',
        '.bash',
        '.zsh',
        '.fish',
        '.bat',
        '.cmd',
        '.sql',
        '.graphql',
        '.gql',
        '.proto',
        '.sol',
        '.vue',
        '.svelte',
        '.astro',
        '.clj',
        '.cljs',
        '.cljc',
        '.edn',
        '.lisp',
        '.cl',
        '.scm',
        '.rkt',
        '.coffee',
        '.litcoffee',
        '.wasm',
        '.wat',
        '.zig',
        '.nim',
        '.v',
        '.vhdl',
        '.vhd',
        '.sv',
        '.tcl',
        '.awk',
        '.sed',
        '.d',
        '.pas',
        '.pp',
        '.cob',
        '.cbl',
        '.ada',
        '.adb',
        '.ads',
      ],
      mapping: { icon: FileCode, color: '#3178C6' },
    },
    {
      extensions: [
        '.ini',
        '.cfg',
        '.conf',
        '.config',
        '.properties',
        '.prop',
        '.lock',
        '.log',
        '.rtf',
        '.tex',
        '.bib',
        '.adoc',
        '.asciidoc',
        '.rst',
        '.org',
        '.wiki',
        '.nfo',
        '.diff',
        '.patch',
        '.ics',
        '.vcf',
        '.xsd',
        '.xsl',
        '.xslt',
        '.dtd',
        '.gradle',
        '.editorconfig',
        '.htaccess',
        '.dockerignore',
        '.gitattributes',
        '.gitmodules',
        '.npmrc',
        '.yarnrc',
        '.babelrc',
        '.prettierrc',
        '.eslintrc',
        '.stylelintrc',
        '.browserslistrc',
        '.plist',
        '.strings',
      ],
      mapping: { icon: FileText, color: '#6B7280' },
    },
    {
      extensions: [
        '.bmp',
        '.webp',
        '.avif',
        '.ico',
        '.tif',
        '.tiff',
        '.heic',
        '.heif',
        '.raw',
        '.cr2',
        '.cr3',
        '.nef',
        '.arw',
        '.dng',
        '.orf',
        '.rw2',
        '.psd',
        '.ai',
        '.eps',
        '.indd',
        '.sketch',
        '.xcf',
        '.exr',
        '.hdr',
        '.jxl',
        '.jp2',
        '.j2k',
        '.pbm',
        '.pgm',
        '.ppm',
        '.pnm',
        '.apng',
      ],
      mapping: { icon: FileImage, color: '#9333EA' },
    },
    {
      extensions: [
        '.bz',
        '.bz2',
        '.xz',
        '.lz',
        '.lzma',
        '.zst',
        '.cab',
        '.iso',
        '.dmg',
        '.img',
        '.vhdx',
        '.wim',
        '.deb',
        '.rpm',
        '.apk',
        '.aab',
        '.ipa',
        '.jar',
        '.war',
        '.ear',
        '.whl',
        '.egg',
        '.nupkg',
        '.tgz',
        '.tbz',
        '.tbz2',
        '.txz',
        '.cpio',
        '.ar',
        '.lzh',
        '.sit',
        '.sitx',
      ],
      mapping: { icon: FileArchive, color: '#D97706' },
    },
    {
      extensions: [
        '.aac',
        '.ogg',
        '.oga',
        '.opus',
        '.m4a',
        '.wma',
        '.aiff',
        '.aif',
        '.ape',
        '.alac',
        '.mid',
        '.midi',
        '.mka',
        '.amr',
        '.ac3',
        '.dts',
        '.m3u',
        '.m3u8',
        '.pls',
        '.cue',
        '.kar',
        '.ra',
        '.snd',
        '.au',
        '.voc',
      ],
      mapping: { icon: FileAudio, color: '#10B981' },
    },
    {
      extensions: [
        '.mov',
        '.wmv',
        '.flv',
        '.webm',
        '.m4v',
        '.mpeg',
        '.mpg',
        '.mpe',
        '.3gp',
        '.3g2',
        '.tsv',
        '.mts',
        '.m2ts',
        '.vob',
        '.ogv',
        '.rm',
        '.rmvb',
        '.asf',
        '.f4v',
        '.divx',
        '.xvid',
        '.mxf',
        '.swf',
        '.qt',
      ],
      mapping: { icon: FileVideo, color: '#EF4444' },
    },
    {
      extensions: [
        '.ods',
        '.ots',
        '.xlsm',
        '.xlsb',
        '.xlt',
        '.xltx',
        '.numbers',
        '.parquet',
        '.feather',
        '.arrow',
        '.dbf',
        '.sav',
        '.sas7bdat',
        '.dta',
        '.por',
        '.dif',
        '.sylk',
        '.slk',
        '.tab',
      ],
      mapping: { icon: FileSpreadsheet, color: '#059669' },
    },
    {
      extensions: [
        '.pdf',
        '.doc',
        '.docx',
        '.docm',
        '.dot',
        '.dotx',
        '.odt',
        '.ott',
        '.pages',
        '.epub',
        '.mobi',
        '.azw',
        '.azw3',
        '.fb2',
        '.djvu',
        '.ppt',
        '.pptx',
        '.pptm',
        '.odp',
        '.key',
      ],
      mapping: { icon: FileText, color: '#2563EB' },
    },
  ];

  for (const group of extensionGroups) {
    if (group.extensions.includes(ext)) return group.mapping;
  }

  return { icon: File, color: '#6B7280' };
}
