// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Adapter 能力标志位。
 *
 * UI 据此数据驱动地决定显示哪些列与操作（如 WebDAV 隐藏 owner/permissions 列）。
 * 前端以数值形式接收，可用位运算判断能力。
 *
 * 注：使用 transparent newtype 而非 `bitflags!` 宏，因 ts-rs 11 不支持
 * 在 `bitflags!` 生成的类型上 derive `TS`。
 */
export type AdapterCapability = number;
