// This file is generated by ts-rs.
// Do NOT edit manually — run `cargo test --test export_types` to regenerate.
// MANUAL PLACEHOLDER: 待 ts-rs 自动覆盖。
// 注：AdapterCapability 在 Rust 端为 transparent newtype(u32)，
// ts-rs 导出为 number 类型别名。

export type AdapterCapability = number;
