// This file is generated by ts-rs.
// Do NOT edit manually — run `cargo test --test export_types` to regenerate.
// MANUAL PLACEHOLDER: 待 ts-rs 自动覆盖。

export type ErrorCode =
  | "connection_failed"
  | "auth_failed"
  | "not_connected"
  | "connection_timeout"
  | "host_unreachable"
  | "file_not_found"
  | "permission_denied"
  | "file_already_exists"
  | "directory_not_empty"
  | "protocol_error"
  | "unsupported_operation"
  | "storage_read_failed"
  | "storage_write_failed"
  | "crypto_decrypt_failed"
  | "crypto_encrypt_failed"
  | "session_not_found"
  | "session_expired"
  | "operation_cancelled"
  | "operation_timeout"
  | "platform_unsupported";
