// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 文件操作类型。
 */
export type FileOperation =
  | 'download'
  | 'upload'
  | 'delete'
  | 'move'
  | 'rename'
  | 'createDirectory'
  | 'createFile'
  | 'transfer';
