// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 运行平台。
 */
export type Platform = 'windows' | 'macos' | 'linux' | 'ios' | 'android';
