// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 支持的远程文件传输协议。
 *
 * 新增协议时：
 * 1. 在此枚举添加变体；
 * 2. 在 `transport/` 目录新建 adapter 文件；
 * 3. 在 `create_adapter()` 工厂函数注册。
 */
export type Protocol = 'sftp' | 'webdav' | 'ftp' | 's3' | 'scp';
