// This file is generated by ts-rs.
// Do NOT edit manually — run `cargo test --test export_types` to regenerate.
// MANUAL PLACEHOLDER: 环境限制（GNU 工具链 DLL 链）导致 ts-rs 无法运行时执行，
// 本文件为手工占位，待 MSVC 环境就绪后由 ts-rs 自动覆盖。

export type Protocol = "sftp" | "webDav" | "ftp" | "s3" | "scp";
