// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 文件列表排序列。
 */
export type SortColumn = "name" | "size" | "lastModified" | "owner" | "permissions";
