// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 文件传输方向。
 */
export type TransferDirection = 'localToRemote' | 'remoteToLocal' | 'remoteToRemote';
