// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 保险库同步生命周期阶段。
 */
export type VaultSyncPhase = 'idle' | 'pending' | 'syncing' | 'failed';
